version: 2
jobs:
  build:
    working_directory: ~/phovea
    docker:
      - image: caleydo/phovea_circleci_python:v2.0
    steps:
      - checkout
      - run:
          command: |
            (!(test -f docker_packages.txt) || (cat docker_packages.txt | xargs sudo apt-get install -y))
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements_dev.txt" }}
      - run:
          name: install-pip-wee
          command: |
            virtualenv ~/venv
            . ~/venv/bin/activate
            pip install -r requirements_dev.txt
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements_dev.txt" }}
          paths:
          - ~/venv
      - run: #force update of VCS dependencies?
          name: update-pip-vcs-dependencies
          command: |
            . ~/venv/bin/activate
            pip install --upgrade --upgrade-strategy=only-if-needed -r requirements.txt
      - run:
          name: dist
          command: |
            . ~/venv/bin/activate
            npm run dist
      - store_artifacts:
          path: dist
          prefix: dist
workflows:
  version: 2
#  build-nightly:
#    triggers:
#      - schedule: # nightly build during weekday
#          cron: "15 1 * * 1-5"
#          filters:
#            branches:
#              only:
#                - develop
#    jobs:
#      - build
  build-branch:
    jobs:
      - build:
          filters:
            tags:
              ignore: /^v.*/
  build-tag:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
