version: 2
jobs:
  build:
    working_directory: ~/phovea
    docker:
      - image: circleci/python:3.7-node-browsers
        environment:
          NODE_VERSION: 10.16.3
    tags:
      - /v\d+.\d+.\d+.*/
    steps:
      - checkout
      - run:
          command: |
            (!(test -f docker_packages.txt) || (cat docker_packages.txt | xargs sudo apt-get install -y))
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements_dev.txt" }}
      - run:
          name: install-pip-wee
          command: |
            virtualenv ~/venv
            . ~/venv/bin/activate
            pip install -r requirements_dev.txt
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements_dev.txt" }}
          paths:
          - ~/venv
      - run: #force update of VCS dependencies?
          name: update-pip-vcs-dependencies
          command: |
            . ~/venv/bin/activate
            pip install --upgrade --upgrade-strategy=only-if-needed -r requirements.txt
      - run:
          name: dist
          command: |
            . ~/venv/bin/activate
            npm run dist
      - store_artifacts:
          path: dist
          prefix: dist
